### PR TITLE
Fix sectorMu deadlocks

### LINKED ISSUE #52: Host sectorMu deadlock
@lukechampine @ChrisSchinnerl #50 introduced a deadlock on startup: 

https://github.com/SiaFoundation/siad/blob/9846fccdd0ee2253c7c4e0b2ac73823917f46c4f/modules/host/contractmanager/contractmanager.go#L229

https://github.com/SiaFoundation/siad/blob/9846fccdd0ee2253c7c4e0b2ac73823917f46c4f/modules/host/contractmanager/persist.go#L165 

Does it make sense to remove the lock from `loadSectorLocations` and refactor `threadedFolderRecheck`?

### PR DESCRIPTION
**Pull request by n8maninger**
This fixes the two issues I noticed in #50

+ Fixes a deadlock on startup when calling `loadSectorLocations` from `newContractManager`.
+ Fixes a deadlock in `managedLockSector` when waiting to acquire a sector lock.
+ Remove usage of `lockSector` to prevent holding `sectorMu` while potentially waiting on it in `managedUnlockSector`

Closes #52

### CODE REVIEW

**Comment by lukechampine** [comment]
Looks alright to me, but I'd feel more confident if @ChrisSchinnerl review this as well.

File: modules/host/contractmanager/storagefolder.go [hunk 1]
```diff
@@ -315,13 +315,8 @@ func (cm *ContractManager) threadedFolderRecheck() {
...
 		cm.wal.mu.Lock()
 		cm.sectorMu.Lock()
-		sfs := make([]*storageFolder, 0, len(cm.storageFolders))
-		for _, sf := range cm.storageFolders {
-			sfs = append(sfs, sf)
-		}
-		cm.sectorMu.Unlock()
 
-		for _, sf := range sfs {
+		for _, sf := range cm.storageFolders {
```
Comment (ChrisSchinnerl) [inline modules/host/contractmanager/storagefolder.go:319]: Did this cause issues as well? The reason I copied the folders first was to avoid opening a file while holding `sectorMu` every second we trigger the recheck.

But I guess if we only do this once per storage folder and the remaining times we just check the atomic and skip opening the file it's fine.

**Review by ChrisSchinnerl — APPROVED** [review]

File: modules/host/contractmanager/storagefolder.go (hunk 1 above)
Comment (n8maninger) [reply modules/host/contractmanager/storagefolder.go:319]: It wasn't causing problems, but it seemed like the safer route after removing `sectorMu` from `loadSectorLocations`. I'll put the copy back and also wrap `loadSectorLocations`.

Comment (n8maninger) [reply modules/host/contractmanager/storagefolder.go:319]: Do the changes look okay with what you were going for?

**Comment by n8maninger** [comment]
@lukechampine look good? Looks like only the flaky renter tests failed.
