### PR TITLE
fix high disk usage when host is idle

### LINKED ISSUE #17: High write activity by contractmanager
# BUG REPORT
`siad` is writing 5MB/s to 10MB/s constantly, which is causing high wear on SSD and is not sustainable. I could move sia folder to HDD, but HDD is not that reliable and has higher risk of losing host db and other sia files. Running strace on siad shows that all writes are around `contractmanager/contractmanager.json`, `contractmanager/contractmanager.json_temp` mostly and little bit `contractmanager/contractmanager.wal` (refer to strace output below). Also, I have attached screenshot of how much write siad is doing. You can see when I stop siad service around 17:48 mark, all disk activity goes idle. Once I start the siad again (in a minute), I have lots of write. When hosting 24/7, this results a lot of disk write on the host.  

## Stack Trace or error message
```
root@ubuntu:~# strace -f -e trace=file -p 1032273
strace: Process 1032273 attached with 13 threads
[pid 1032282] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032282] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032282] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032282] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032498] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032498] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032498] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032498] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=1032273, si_uid=0} ---
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032273] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032281] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032281] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032281] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032497] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032497] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032273] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032273] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032277] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032277] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032277] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032277] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032281] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 104
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032282] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032282] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032282] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032279] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal", {st_mode=S_IFREG|0644, st_size=893, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032279] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032279] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal") = 0
[pid 1032279] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 13
[pid 1032279] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 104
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032273] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032273] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032277] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032280] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032280] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032280] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032280] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032280] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032280] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032273] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032273] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032273] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032273] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032497] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032281] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032281] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 53
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json", {st_mode=S_IFREG|0644, st_size=1342319, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032497] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json") = 0
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] newfstatat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal", {st_mode=S_IFREG|0644, st_size=894, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032281] renameat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal_temp", AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal") = 0
[pid 1032281] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.wal_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 13
[pid 1032497] openat(AT_FDCWD, "/root/sia/host/contractmanager/contractmanager.json_temp", O_RDWR|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
[pid 1032281] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] <... openat resumed>)     = 53
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
[pid 1032497] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1032273, si_uid=0} ---
```

## Expected Behavior
minimal write amplification.

## Observed Behavior
image

## How to reproduce it (as minimally and precisely as possible)
Run `siad` with `-M gctwh` modules. It is more pronounced on hosts that have been active for couple months (has many contracts).

## Environment
* Sia version:
```
Sia Client
	Version 1.5.6
	Git Revision 0b253ab18
	Build Time   2021-04-16 13:04:14 -0400
Sia Daemon
	Version 1.5.6
	Git Revision 0b253ab18
	Build Time   2021-04-16 13:04:14 -0400
```
* OS: `Ubuntu 20.04.2 LTS 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by n8maninger**
The order of `savedSettings.StorageFolders` was changing causing `reflect.DeepEqual` to fail and constant writes to `contractmanager.json`.

Closes #17

### CODE REVIEW

File: modules/host/contractmanager/persist.go [hunk 1]
```diff
@@ -31,6 +32,34 @@ type (
 	}
 )
 
+func (sf *savedStorageFolder) Equals(sfb savedStorageFolder) bool {
```
Comment (lukechampine) [inline modules/host/contractmanager/persist.go:35]: this should probably be inlined into `savedSettings.Equals`. It's not likely to be useful on its own.

File: modules/host/contractmanager/persist.go [hunk 2]
```diff
@@ -31,6 +32,34 @@ type (
...
+	for i := range sf.Usage {
+		if sf.Usage[i] != sfb.Usage[i] {
+			return false
+		}
+	}
+
+	return true
+}
+
+func (s *savedSettings) Equals(sb savedSettings) bool {
```
Comment (lukechampine) [inline modules/host/contractmanager/persist.go:49]: no need to export this. Also, convention (in the `siad` repo, at least) is to add docstrings to all methods.

File: modules/host/contractmanager/persist.go [hunk 3]
```diff
@@ -162,5 +191,9 @@ func (cm *ContractManager) savedSettings() savedSettings {
 			sf.setUsage(sectorIndex)
 		}
 	}
+
+	sort.Slice(ss.StorageFolders, func(i, j int) bool {
+		return ss.StorageFolders[i].Index < ss.StorageFolders[j].Index
+	})
```
Comment (lukechampine) [inline modules/host/contractmanager/persist.go:197]: should have a comment like:

```go
// canonicalize storage folder ordering; otherwise savedSettings.equals
// could return false for equivalent settings
```

File: modules/host/contractmanager/persist_test.go [hunk 4]
```diff
@@ -26,6 +26,365 @@ func (*dependencyNoRecheck) Disrupt(s string) bool {
...
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			if got := tt.folder.Equals(tt.expected); got != tt.want {
+				t.Errorf("savedStorageFolder.Equals() = %v, want %v", got, tt.want)
+			}
+		})
+	}
+}
+
+func Test_savedSettings_Equals(t *testing.T) {
```
Comment (lukechampine) [inline modules/host/contractmanager/persist_test.go:150]: conventionally we don't use `_` in test names; everything is squished together and capitalized if necessary. I can't think of this ever causing issues in practice, because it's very rare to have two types or methods with the same name (where one is exported).

File: modules/host/contractmanager/persist_test.go [hunk 5]
```diff
@@ -26,6 +26,365 @@ func (*dependencyNoRecheck) Disrupt(s string) bool {
...
+	tests := []struct {
+		name     string
+		settings savedSettings
+		expected savedSettings
```
Comment (lukechampine) [inline modules/host/contractmanager/persist_test.go:154]: `expected` is kind of an odd name for testing an `equals` methods. I would just call these `a` and `b`. I generally use `expected` where you use `want` (but `want` is fine).

File: modules/host/contractmanager/persist_test.go [hunk 6]
```diff
@@ -26,6 +26,365 @@ func (*dependencyNoRecheck) Disrupt(s string) bool {
...
+		want     bool
+	}{
+		{
+			name: "equal",
+			settings: savedSettings{
+				SectorSalt: crypto.HashBytes([]byte{1}),
```
Comment (lukechampine) [inline modules/host/contractmanager/persist_test.go:160]: `crypto.Hash{1}` will also work

File: modules/host/contractmanager/persist_test.go [hunk 7]
```diff
@@ -26,6 +26,365 @@ func (*dependencyNoRecheck) Disrupt(s string) bool {
...
+				StorageFolders: []savedStorageFolder{
+					{
+						Index: 1,
+						Path:  "/tmp/storage/01",
+						Usage: []uint64{
+							5,
+							1,
+							2,
+							3,
+							4,
```
Comment (lukechampine) [inline modules/host/contractmanager/persist_test.go:170]: ok, now I'm just being picky, but it bothers me to have these on separate lines. I would probably condense this all the way down to:

```go
{Index: 1, Path:  "/tmp/storage/01", Usage: []uint64{5, 1, 2, 3, 4}},
```
this will make any differences between the two objects more readily apparent as well.

File: modules/host/contractmanager/persist.go (hunk 3 above)
Comment (lukechampine) [reply modules/host/contractmanager/persist.go:197]: I'll also note that this is the most "dangerous" part of the diff, because it affects the data being written to disk. I'm confident that this won't cause any breakage, but if we were being *really* conservative, we'd probably want to perform the sort in `equals` (after copying the memory, to prevent side effects).

**Review by lukechampine — COMMENTED** [review]
Looks good! Thanks for tackling this quickly.
